#person:
#    lastName: hello
#    age: 18
#    boss: false
#    birth: 2017/12/12
#    maps: {k1: 'v1',k2: '12'}
#    lists: bascketball,lol,travel
#    dog:
#      age: 18
#      name: '小狗'

spring:
  profiles:
    active: dev
---
spring:
 profiles: dev
server:
  port: 8081

---
spring:
  profiles: test
server:
  port: 8080